version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: xfer_db
      POSTGRES_USER: xfer_user
      POSTGRES_PASSWORD: xfer_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xfer_user -d xfer_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Application
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://xfer_user:xfer_password@postgres:5432/xfer_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - SECRET_KEY=your-super-secret-key-change-in-production
      - DEBUG=True
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001
      - ADMIN_WALLET_ADDRESS=TAQ2TfR4Pk6GPstVPExPo4QvdwcyJTzDSf
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "
        python -m alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  # Celery Worker
  celery-worker:
    build: .
    environment:
      - DATABASE_URL=postgresql+asyncpg://xfer_user:xfer_password@postgres:5432/xfer_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - SECRET_KEY=your-super-secret-key-change-in-production
      - ADMIN_WALLET_ADDRESS=TAQ2TfR4Pk6GPstVPExPo4QvdwcyJTzDSf
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    command: celery -A app.worker.celery_app worker --loglevel=info

  # Celery Beat (Scheduler)
  celery-beat:
    build: .
    environment:
      - DATABASE_URL=postgresql+asyncpg://xfer_user:xfer_password@postgres:5432/xfer_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - SECRET_KEY=your-super-secret-key-change-in-production
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    command: celery -A app.worker.celery_app beat --loglevel=info

  # Flower (Celery Monitoring)
  flower:
    build: .
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      - redis
    command: celery -A app.worker.celery_app flower --port=5555

volumes:
  postgres_data:
  redis_data: