"""Add admin wallets and bank accounts tables

Revision ID: 865700eeb511
Revises: 001
Create Date: 2025-06-30 17:12:03.101858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865700eeb511'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_bank_accounts', 'id',
               existing_type=sa.NUMERIC(),
               type_=app.core.database_types.UUIDString(length=36),
               existing_nullable=False)
    op.alter_column('admin_wallets', 'id',
               existing_type=sa.NUMERIC(),
               type_=app.core.database_types.UUIDString(length=36),
               existing_nullable=False)
    op.alter_column('transfer_requests', 'transfer_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index('ix_transfer_requests_transfer_id', table_name='transfer_requests')
    op.create_unique_constraint(None, 'transfer_requests', ['transfer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfer_requests', type_='unique')
    op.create_index('ix_transfer_requests_transfer_id', 'transfer_requests', ['transfer_id'], unique=False)
    op.alter_column('transfer_requests', 'transfer_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('admin_wallets', 'id',
               existing_type=app.core.database_types.UUIDString(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('admin_bank_accounts', 'id',
               existing_type=app.core.database_types.UUIDString(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###