"""Add admin wallets and bank accounts tables

Revision ID: a66c5842fa6b
Revises: 001
Create Date: 2025-06-30 17:09:42.854011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a66c5842fa6b'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wallets_address', table_name='wallets')
    op.drop_table('wallets')
    op.drop_index('ix_admins_email', table_name='admins')
    op.drop_table('admins')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_transfer_requests_transfer_id', table_name='transfer_requests')
    op.drop_table('transfer_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_requests',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=20, scale=8), nullable=False),
    sa.Column('fee', sa.NUMERIC(precision=20, scale=8), nullable=False),
    sa.Column('net_amount', sa.NUMERIC(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('status_message', sa.TEXT(), nullable=True),
    sa.Column('priority', sa.VARCHAR(length=10), nullable=True),
    sa.Column('crypto_tx_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('deposit_wallet_address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('admin_wallet_address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('confirmation_count', sa.NUMERIC(precision=3, scale=0), nullable=True),
    sa.Column('required_confirmations', sa.NUMERIC(precision=3, scale=0), nullable=True),
    sa.Column('bank_account_info', sqlite.JSON(), nullable=True),
    sa.Column('bank_accounts', sqlite.JSON(), nullable=True),
    sa.Column('processed_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('processing_notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('transfer_id', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transfer_requests_transfer_id', 'transfer_requests', ['transfer_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('kyc_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('kyc_documents', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('verification_token', sa.VARCHAR(length=255), nullable=True),
    sa.Column('verification_code', sa.VARCHAR(length=6), nullable=True),
    sa.Column('verification_code_expires', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('admins',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=True),
    sa.Column('permissions', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_super_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('api_key', sa.VARCHAR(length=255), nullable=True),
    sa.Column('api_key_expires_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('login_attempts', sa.VARCHAR(length=10), nullable=True),
    sa.Column('locked_until', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_index('ix_admins_email', 'admins', ['email'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=False),
    sa.Column('network', sa.VARCHAR(length=20), nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=20, scale=8), nullable=True),
    sa.Column('pending_balance', sa.NUMERIC(precision=20, scale=8), nullable=True),
    sa.Column('frozen_balance', sa.NUMERIC(precision=20, scale=8), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('wallet_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('last_transaction_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_activity_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wallets_address', 'wallets', ['address'], unique=False)
    # ### end Alembic commands ###