"""Add admin wallets and bank accounts tables

Revision ID: e81ea286a998
Revises: 001
Create Date: 2025-06-30 17:12:26.445648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81ea286a998'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create admin_wallets table
    op.create_table('admin_wallets',
        sa.Column('id', sa.String(length=36), primary_key=True),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('address', sa.String(length=255), nullable=False, unique=True, index=True),
        sa.Column('currency', sa.String(length=10), nullable=False, default='USDT'),
        sa.Column('network', sa.String(length=20), nullable=False, default='TRC20'),
        sa.Column('fee_percentage', sa.Numeric(precision=5, scale=2), default=0),
        sa.Column('is_active', sa.Boolean(), default=True),
        sa.Column('is_primary', sa.Boolean(), default=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('last_transaction_hash', sa.String(length=255), nullable=True),
        sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now())
    )
    
    # Create admin_bank_accounts table
    op.create_table('admin_bank_accounts',
        sa.Column('id', sa.String(length=36), primary_key=True),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('bank_name', sa.String(length=100), nullable=False),
        sa.Column('account_number', sa.String(length=50), nullable=False),
        sa.Column('routing_number', sa.String(length=50), nullable=True),
        sa.Column('account_type', sa.String(length=20), nullable=False),
        sa.Column('fee_percentage', sa.Numeric(precision=5, scale=2), default=0),
        sa.Column('is_active', sa.Boolean(), default=True),
        sa.Column('is_primary', sa.Boolean(), default=False),
        sa.Column('account_holder_name', sa.String(length=100), nullable=True),
        sa.Column('swift_code', sa.String(length=50), nullable=True),
        sa.Column('iban', sa.String(length=50), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now())
    )
    
    # Create indexes
    op.create_index('ix_admin_wallets_address', 'admin_wallets', ['address'])
    op.create_index('ix_admin_wallets_is_primary', 'admin_wallets', ['is_primary'])
    op.create_index('ix_admin_wallets_is_active', 'admin_wallets', ['is_active'])
    op.create_index('ix_admin_bank_accounts_is_primary', 'admin_bank_accounts', ['is_primary'])
    op.create_index('ix_admin_bank_accounts_is_active', 'admin_bank_accounts', ['is_active'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('ix_admin_bank_accounts_is_active', table_name='admin_bank_accounts')
    op.drop_index('ix_admin_bank_accounts_is_primary', table_name='admin_bank_accounts')
    op.drop_index('ix_admin_wallets_is_active', table_name='admin_wallets')
    op.drop_index('ix_admin_wallets_is_primary', table_name='admin_wallets')
    op.drop_index('ix_admin_wallets_address', table_name='admin_wallets')
    
    # Drop tables
    op.drop_table('admin_bank_accounts')
    op.drop_table('admin_wallets')
    
    # ### end Alembic commands ###